name: Run searches
on: push
jobs:
  run-game:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
            python-version: '3.x'
            cache: 'pip'
      - name: Install dependencies
        run: pip install numpy
      - name: Run the game
        run: python3 src/reversi_auto_server.py